"""Shared constants for reconciliation passes."""

from __future__ import annotations

from ..schema.block_types import CAPTION, DISPLAY_BLOCK, FIGURE, LIST_ITEM, PARAGRAPH, TABLE_CONTINUATION

TERMINAL_PUNCT = set('。？！!?；;：:.”’\"\'）】》」』')
FLOAT_LIKE_TYPES = {FIGURE, CAPTION, TABLE_CONTINUATION}
MERGEABLE_TEXT_TYPES = {PARAGRAPH, LIST_ITEM, DISPLAY_BLOCK}
DISPLAY_BLOCK_TYPES = {DISPLAY_BLOCK}

_DEFAULT_PAGE_HEIGHT = 1000.0
_NEAR_PAGE_BOTTOM_RATIO = 0.82
_NEAR_PAGE_TOP_RATIO = 0.22
_DISPLAY_MIN_LEFT_MARGIN = 18
_DISPLAY_MIN_WIDTH_RATIO = 0.95
